### ISSUE TITLE
criar arquivo de configuração .editorconfig para padronizar configuração de editores/IDE's

### ISSUE THREAD

**Issue by luzfcb** [Alquimar/bcrsilva#9]
criar arquivo de configuração [.editorconfig](http://editorconfig.org/) para padronizar configuração de editores/IDE's, de modo que a codificação, tipo de final de linha, espaçamento e etc fique o mais independente entre editores/IDE's e diversos sistemas operacionais.

Lembrar de incluir no README um aviso que o programador deve instalar o plugin do editorconfig para o editor/ide preferida

**Comment by Alquimar** [comment]
corrigido nos commits 79055a61818c17ce16c33ff46d38bcb1fcf44f72 e d17038ee593491e2a4951644227657b9b5207fdc
